---
title: "Statistics Production Guidance"
date: "Last updated: `r Sys.Date()`"
author: "By Cam Race, Laura Selby and Sarah Wong"
site: "_site.yml"
---

```{r include=FALSE}
library(fontawesome)

```

---

This website is a guide aimed at anyone producing official statistics in the Department for Education (DfE). It covers wider best practice and pulls together pieces of guidance that were previously standalone documents. If viewed in its entirety, it provides a walk-through guide from processing to publication, as well as being a single reference point that is easy to navigate if you just need to check on a specific part of the process, link off to other resources, or access specific guidance.

Within this guide you can read about: 

## Learning

* [Introduction](l+d.html)  
A collection of useful learning resources, and information on the recommended tools to get you started

* [SQL](sql.html)  
Guidance and tips for using the programming language SQL

* [R](r.html)  
Guidance and tips for using the programming language R

* [Git](git.html)  
Guidance and tips for using the version control software Git

## Creating statistics

* [Processes and RAP](rap.html)  
Guidance for how to process data, including the principles of Reproducible Analytical Pipelines (RAP)

* [Open data standards](ud.html)  
Guidance on how to structure data files

* [Writing and visualising](cd.html)  
Things to consider when writing statistical commentary


## Publishing statistics

* [How to publish](pub.html)  
Guidance for how to publish different types of statistics

* [Using EES](ees.html)  
Guidance for how to use the features in the Explore Education Statistics platform

* [Other options](dashboards.html)  
Guidance for how to use the features in the Explore Education Statistics platform

## Review

* [User engagement](user_eng.html)  
Guidance on understanding and engaging with the users of published statistics

* [EES analytics](user_an.html)  
Guidance on understanding how users are interacting with your statistics published via EES

There is already a wealth of resources out there, and therefore this site unashamedly aims to pool the relevant resources for statistics production into one place. There are some things that this site does not yet have, it will develop and change over time. We hope it can prove a useful resource for everyone from the most experienced of producers, right through to those who are working on their very first publication. If you have any feedback, suggested additions, or wish to challenge any of the guidance, please contact us using the envelope button in the top right corner.

---

## Other resources

We also have a number of other applications for statistics production teams to use to help them in their processes, they can be accessed at the links below when using a DfE device.


### DfE QA app (including the 'data screener'):

 - [https://rsconnect/rsc/dfe-published-data-qa/](https://rsconnect/rsc/dfe-published-data-qa/){target="_blank" rel="noopener noreferrer"}

 - Code hosted at [https://github.com/dfe-analytical-services/dfe-published-data-qa](https://github.com/dfe-analytical-services/dfe-published-data-qa){target="_blank" rel="noopener noreferrer"}

### Explore Education Statistics Analytics:

 - [https://rsconnect/rsc/ees-analytics/](https://rsconnect/rsc/ees-analytics/){target="_blank" rel="noopener noreferrer"}

 - Code is not yet publicly available, contact us if you are interested in seeing it or contributing.

### Publication self-assessment tool:

 - [https://rsconnect/rsc/publication-self-assessment/](https://rsconnect/rsc/publication-self-assessment/){target="_blank" rel="noopener noreferrer"}

 - Code mirrored at [https://github.com/dfe-analytical-services/publication-self-assessment-copy](https://github.com/dfe-analytical-services/publication-self-assessment-copy){target="_blank" rel="noopener noreferrer"}

- Template QA code
[https://github.com/dfe-analytical-services](https://github.com/dfe-analytical-services){target="_blank" rel="noopener noreferrer"}


### dfeR package
- [https://github.com/dfe-analytical-services](https://github.com/dfe-analytical-services){target="_blank" rel="noopener noreferrer"}


---

The code for this guidance website is mirrored at [https://github.com/dfe-analytical-services/stats-production-guidance-copy](https://github.com/dfe-analytical-services/stats-production-guidance-copy){target="_blank" rel="noopener noreferrer"}




