---
  title: "Understanding your users"
---
  
<p class="text-muted">Guidance on engaging with users and understanding how they interact with your publications</p>
    
---

# Introduction

---
    
Our statistics are used by a variety of different user groups.

Some more info on them.

Something on being user centred, why it's important and all the things that back it up like the code of practice and department values.

---
    
# User analytics
    
---

We track analytics of users on Explore Education Statistics using Google Analytics as well as other tools. These analytics can be found on our [EES Analytics dashboard](https://rsconnect/rsc/ees-analytics/){target="_blank" rel="noopener noreferrer"}.

---

# User engagement

---

## ONS Strategy

---

The ONS published a [user engagement strategy](https://gss.civilservice.gov.uk/policy-store/user-engagement-strategy-for-statistics-ensuring-official-statistics-meet-societys-need/){target="_blank" rel="noopener noreferrer"} in February 2021.  

The strategy sets out that many producers of statistics are already carrying out regular and effective user engagement. The strategy aims to build on this good work to embed user engagement as an essential part of a statistician’s role. The strategy sets out a vision and addresses the barriers to effective user engagement via three goals:

1.	Collaboration – collaborate across boundaries to offer a more coherent user experience

2.	Capability – build capability and equip producers of statistics with the practical skills and tools to deliver effective user engagement activities

3.	Culture – strengthen our culture and ensure user engagement is always an ongoing and essential part of a statistics producer’s role

The launch of the strategy, as well as two further videos on the value of user engagement are embedded below.

---

### Strategy launch

---

<div align="center">
<iframe width="640" height="360" src="https://www.youtube.com/embed/n7VYdVpNRXU?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write;  encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

---

### What is user engagement

---

<div align="center">
<iframe width="640" height="360" src="https://www.youtube.com/embed/H91A_9EnQ3U?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

---

### User engagement successes

---

<div align="center">
<iframe width="640" height="360" src="https://www.youtube.com/embed/-8JohrNH2Ak?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

---

## DfE

---

DfE are working with ONS and others to consider how to take forward work in this area.  DfE have put together an initial statement (note that this is in draft and should only be used as a guide internally):

>Work to understand and engage our users is vital to ensuring statistics are suitably and best communicated, and help the department in continuously reflecting and improving products and its services.  DfE welcomes the ONS strategy and collective focus on user engagement.
>
>As part of our efforts to meet wider user needs, the Department has undertaken [extensive user research](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/721729/HiveIT_-_DfE_dissemination_discovery.pdf) over the past few years in development of the new Explore Education Statistics platform to disseminate our statistics. We continue to develop this platform in line with user research and feedback. Through the intelligent use of supporting analytics, we are learning more about how our wide range of users find and use statistics, and how best to tailor our outputs to meet their needs.  This will help us embed user need even more strongly into our statistics development.
>
>In addition and more broadly, the department is working with ONS Best Practice Team to consider guidance around user engagement and how best to take forward the strategy for the department.  In line with this, as part of these developments we will be reviewing and refreshing our current [public-facing user engagement strategy](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/287444/User_engagement_policy.pdf) which will then be reviewed annually.

Teams are encouraged to already start to think about who their users are, the channels they use to understand their needs and the user experience. Publication teams should keep abreast of [user analytics](#user-analytics) to understand more about how users use and access their statistics and whether further improvements could be made. In addition, teams should also think about the ways they can glean feedback on their publication(s), this may include internal checks regards enhancements such as participating in [content design scrum(s)](cd.html#publication-scrums).

---

More details and example case studies to follow.

---